In [4]:
import pandas as pd

In [6]:
df=pd.read_csv('raw_dataset.csv')

In [9]:
df.head()

,S.No,Restaurant Name,Cuisine(s),Rating,Number of Reviews,Cost for Two,Locality,Delivery Time,Type
0,1,Grill Craft Co.,"North Indian, Chinese, and Continental",4.2,207,1200,College Road,NaN,Dine-In Restaurant
1,2,Bakes N Brews - Courtyard by Marriott,"Bakery, Cafe, Desserts",4.3,590,800,Mumbai Naka,NaN,Dine-In Restaurant
2,3,Tomato's,"North Indian, Mexican, Chinese, Asian, Mughlai...",4.3,1317,1800,College Road,NaN,Dine-In Restaurant
3,4,Larive Kitchen And Cocktail,"Beverages, North Indian, Pizza, Chinese, Sushi...",4.4,524,2100,College Road,NaN,Dine-In Restaurant
4,5,Prasadam Bhojnalay,"North Indian, Gujarati",3.9,2293,250,Patil Nagar,NaN,Dine-In Restaurant

In [12]:
df.columns

Index(['S.No', 'Restaurant Name', 'Cuisine(s)', 'Rating', 'Number of Reviews',
       'Cost for Two', 'Locality', 'Delivery Time', 'Type'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No               30 non-null     int64
 1   Restaurant Name    30 non-null     object
 2   Cuisine(s)         30 non-null     object
 3   Rating             30 non-null     float64
 4   Number of Reviews  30 non-null     int64
 5   Cost for Two       30 non-null     int64
 6   Locality           30 non-null     object
 7   Delivery Time      0 non-null      float64
 8   Type               30 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 2.2+ KB

In [17]:
df.isnull().sum()

S.No                  0
Restaurant Name       0
Cuisine(s)            0
Rating                0
Number of Reviews     0
Cost for Two          0
Locality              0
Delivery Time        30
Type                  0
dtype: int64

In [19]:
before_count = len(df)

print("Records Before Cleaning:", before_count)

Records Before Cleaning: 30

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df = df.drop_duplicates()

In [25]:
df.duplicated().sum()

np.int64(0)

In [28]:
df['Number of Reviews'] = df['Number of Reviews'].fillna('Not Available')

In [29]:
df['Delivery Time'] = df['Delivery Time'].fillna('Not Available')

In [30]:
df['Rating'] = df['Rating'].fillna('Not Rated')

In [34]:
df['Cuisine(s)'] = df['Cuisine(s)'].str.replace('BBQ','Barbecue')
df['Cuisine(s)'] = df['Cuisine(s)'].str.replace('Coffee','Cafe')
df['Cuisine(s)'] = df['Cuisine(s)'].str.replace('Indo-Chinese','Chinese')
df['Cuisine(s)'] = df['Cuisine(s)'].str.replace('Cake','Bakery')

In [36]:
df['Cuisine(s)'] = df['Cuisine(s)'].str.strip()

df['Restaurant Name'] = df['Restaurant Name'].str.strip()

In [37]:
df['Type'] = df['Type'].replace({
    'Dine In':'Dine-In Restaurant',
    'Restaurant':'Dine-In Restaurant'
})

In [38]:
df.isnull().sum()

S.No                 0
Restaurant Name      0
Cuisine(s)           0
Rating               0
Number of Reviews    0
Cost for Two         0
Locality             0
Delivery Time        0
Type                 0
dtype: int64

In [39]:
after_count = len(df)

print("Records After Cleaning:", after_count)

Records After Cleaning: 30

In [40]:
df.to_csv('cleaned_dataset.csv', index=False)

In [41]:
from google.colab import files

files.download('cleaned_dataset.csv')